/* Hybrid Training v36.120: personalized calibration + swim logging layer. */
(()=>{
'use strict';
const core=window.HybridCore;if(!core)return;
const VER='36.120',PREF='hybridPersonalizationV36120',SWIM='hybridSwimMetadataV36120';
const originals={getState:core.getState?.bind(core),readiness:core.readiness?.bind(core),hybridAdaptationState:core.hybridAdaptationState?.bind(core),effectiveEffortRpe:core.effectiveEffortRpe?.bind(core)};
const DEFAULTS={entryMode:'lengths',preset:'home21',presets:{home21:{label:'Home — 21 yd',length:21,unit:'yd'},yd25:{label:'25 yd pool',length:25,unit:'yd'},m25:{label:'25 m pool',length:25,unit:'m'},m50:{label:'50 m pool',length:50,unit:'m'},custom:{label:'Custom',length:0,unit:'yd'}}};
const FEEL={'too easy':[4.5,1.7],easy:[6,1.15],comfortable:[7,.8],challenging:[8,1],'very hard':[9.5,1.7],'too hard':[9.5,1.7]};
const CARDIO=/(run|walk|swim|bike|cycling|cycle|row|ruck|conditioning|lss|tempo|sprint|hill|stair|elliptical|cardio)/i;
const n=v=>Number.isFinite(+v)?+v:0,clone=v=>JSON.parse(JSON.stringify(v));
const read=(k,d)=>{try{return Object.assign(clone(d),JSON.parse(localStorage.getItem(k)||'{}'))}catch{return clone(d)}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const prefs=()=>read(PREF,DEFAULTS);const setPrefs=x=>{const p=prefs();Object.assign(p,x);write(PREF,p);return p};
const day=s=>{const t=Date.parse((s||'')+'T12:00:00Z');return Number.isFinite(t)?Math.floor(t/864e5):0};
const isCardio=r=>!!r&&(r.conditioning||String(r.session||'').toLowerCase()==='conditioning'||CARDIO.test(r.exercise||''));
function duration(r){const activity=n(r?.metrics?.time);if(isCardio(r)&&activity>0)return [activity,'activity-metrics-time'];const tracked=n(r?.trackedSessionDurationMinutes);if(tracked>0)return [tracked,'tracked-session'];const session=n(r?.sessionDurationMinutes);return [session,session>0?'session-duration':'none']}
function key(r){return [r?.date||'',r?.sessionId||'',r?.exercise||'',r?.completedAt||''].join('|')}function loose(r){return [r?.date||'',r?.session||'',r?.exercise||''].join('|')}
function normalize(state){
 (state?.logs||[]).forEach(r=>{const [mins,source]=duration(r);if(mins>0){if(source==='activity-metrics-time'){const old=n(r.sessionDurationMinutes);if(old&&Math.abs(old-mins)>.01&&r.loggingSessionDurationMinutes==null)r.loggingSessionDurationMinutes=old;r.sessionDurationMinutes=mins}r.effectiveDurationMinutes=mins;r.durationSource=source}});
 const meta=read(SWIM,{byLog:{},pending:{}});(state?.logs||[]).filter(r=>/swim/i.test(r.exercise||'')).forEach(r=>Object.assign(r,meta.byLog?.[key(r)]||meta.pending?.[loose(r)]||{}));return state;
}
function observed(r){const exact=n(r?.rpe);if(exact>0)return [exact,1.45];const f=String(r?.feel||'').trim().toLowerCase();return FEEL[f]||null}
const predicted=r=>n(r?.modelExpectedRpe)||n(r?.modelPlannedExpectedRpe);
function calibration(exercise,state){
 const rows=(state?.logs||[]).filter(r=>r.exercise===exercise).map(r=>({r,o:observed(r),p:predicted(r)})).filter(x=>x.o&&x.p>0);if(!rows.length)return {exercise,n:0,effectiveN:0,correction:0,confidence:0,label:'Learning'};
 const extremes=rows.filter(x=>['too easy','very hard','too hard'].includes(String(x.r.feel||'').toLowerCase()));let boost=1;if(extremes.length>=2){const signs=extremes.map(x=>Math.sign(x.o[0]-x.p)).filter(Boolean);if(signs.length>=2&&signs.every(s=>s===signs[0]))boost=Math.min(1.5,1+.12*(signs.length-1))}
 let sw=0,se=0,sq=0;rows.forEach(x=>{const age=Math.max(0,day(new Date().toISOString().slice(0,10))-day(x.r.date)),ext=['too easy','very hard','too hard'].includes(String(x.r.feel||'').toLowerCase()),w=x.o[1]*Math.exp(-age/56)*(ext?boost:1),err=Math.max(-3,Math.min(3,x.o[0]-x.p));sw+=w;se+=w*err;sq+=w*w});
 const eff=sw*sw/(sq||1),raw=se/(sw||1),cor=Math.max(-1.75,Math.min(1.75,raw*(eff/(eff+3.5)))),conf=Math.min(.95,1-Math.exp(-eff/5));return {exercise,n:rows.length,effectiveN:+eff.toFixed(2),correction:+cor.toFixed(2),confidence:+conf.toFixed(2),label:conf>=.65?'Established':conf>=.35?'Emerging':'Learning'};
}
function annotate(state){const c={};(state?.logs||[]).forEach(r=>{if(!r.exercise||!predicted(r))return;const x=c[r.exercise]||(c[r.exercise]=calibration(r.exercise,state));r.personalEffortCorrection=x.correction;r.personalCalibrationConfidence=x.confidence;r.personalExpectedRpe=Math.max(1,Math.min(10,+(predicted(r)+x.correction).toFixed(1)))})}
function weightGate(state){const a=Object.entries(state?.bodyweightMeasurements||{}).map(([date,x])=>({date,lb:n(x?.lb)})).filter(x=>x.lb>0).sort((a,b)=>a.date.localeCompare(b.date)),span=a.length>1?day(a.at(-1).date)-day(a[0].date):0,ready=a.length>=7&&span>=14;return {ready,entries:a.length,spanDays:span,label:ready?'Trend established':'Early estimate — insufficient data'}}
function recoveryAuthority(state){const s=state?.adaptiveModelSnapshot||{},nr=s.neuromuscularReadiness||{},back=s.shadowBacktest||s.adaptiveBacktest?.shadowBacktest||{},passed=Array.isArray(back.passed)?back.passed:[],validated=passed.length>0&&(n(nr.effectiveN)>=8||n(nr.confidence)>=.7);return {validated,authority:validated?'programming':'informational',note:validated?'Personal recovery signals cleared validation gates.':'Personal recovery signals are still learning; they remain informational and should not materially down-regulate training by themselves.'}}
function state(){const s=originals.getState?originals.getState():{};normalize(s);annotate(s);const g=weightGate(s);if(s.bodyweightSnapshot){s.bodyweightSnapshot.personalTrendReady=g.ready;s.bodyweightSnapshot.personalTrendLabel=g.label;s.bodyweightSnapshot.personalTrendSpanDays=g.spanDays}return s}
core.getState=state;
if(originals.readiness)core.readiness=function(...args){const r=originals.readiness(...args),a=recoveryAuthority(state());return r&&typeof r==='object'?Object.assign({},r,{personalRecoveryAuthority:a.authority,personalRecoveryValidated:a.validated,personalRecoveryNote:a.note}):r};
if(originals.hybridAdaptationState)core.hybridAdaptationState=function(...args){const r=originals.hybridAdaptationState(...args);if(!r||typeof r!=='object')return r;const g=weightGate(state()),out=Object.assign({},r,{bodyweightTrendGate:g});if(!g.ready&&out.weight)out.weight=Object.assign({},out.weight,{direction:'unknown',displayRate:false,displayLabel:g.label,confidence:Math.min(n(out.weight.confidence),.12)});return out};
if(originals.effectiveEffortRpe)core.effectiveEffortRpe=function(r){const o=observed(r);return o?o[0]:originals.effectiveEffortRpe(r)};
function swimDistance(count,length,unit='yd'){return {distance:+(Math.max(0,n(count))*Math.max(0,n(length))).toFixed(2),unit,lengthCount:Math.max(0,n(count)),poolLength:Math.max(0,n(length))}}
function find(card,rx){for(const l of card.querySelectorAll('label'))if(rx.test(l.textContent||'')){const x=l.querySelector('input,select,textarea');if(x)return x}return null}
function native(el,v){if(!el)return;el.value=String(v);el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))}
const currentExercise=card=>{try{return core.currentCardExercise?.(card)||card.dataset.plannedExercise||card.querySelector('.log-title')?.textContent?.trim()||''}catch{return card.dataset.plannedExercise||''}};
function persistSwim(card,m){const st=read(SWIM,{byLog:{},pending:{}}),k=[document.querySelector('#logDate')?.value||new Date().toISOString().slice(0,10),document.querySelector('#logSession')?.value||'Conditioning',currentExercise(card)].join('|');st.pending=st.pending||{};st.pending[k]=m;write(SWIM,st)}
function updateSwim(card,h){const p=prefs(),mode=h.querySelector('[name="v36120mode"]:checked')?.value||p.entryMode,preset=h.querySelector('.v36120-preset')?.value||p.preset;setPrefs({entryMode:mode,preset});const custom=preset==='custom',box=h.querySelector('.v36120-custom');box.hidden=!custom;h.querySelector('.v36120-lengths').hidden=mode!=='lengths';if(mode!=='lengths'){persistSwim(card,{distanceEntryMode:'distance',poolPreset:preset});return}const cfg=custom?{length:n(h.querySelector('.v36120-custom-length').value),unit:h.querySelector('.v36120-custom-unit').value}:p.presets[preset],count=n(h.querySelector('.v36120-count').value),out=swimDistance(count,cfg.length,cfg.unit);h.querySelector('.v36120-preview').textContent=count&&cfg.length?`${count} lengths × ${cfg.length} ${cfg.unit} = ${out.distance} ${cfg.unit}`:'One length = one one-way traversal.';if(count&&cfg.length){const d=find(card,/distance/i)||card.querySelector('input[name*="distance" i],[data-field="distance"] input');native(d,out.distance);const u=find(card,/distance unit|unit/i);if(u?.options){const opt=[...u.options].find(o=>String(o.value).toLowerCase()===cfg.unit||String(o.textContent).toLowerCase().includes(cfg.unit));if(opt)native(u,opt.value)}persistSwim(card,{distanceEntryMode:'lengths',lengthCount:count,poolLength:cfg.length,poolLengthUnit:cfg.unit,poolPreset:preset,calculatedDistance:out.distance})}}
function addSwim(card){if(card.querySelector('.v36120-swim')||!/swim/i.test(currentExercise(card)))return;const p=prefs(),h=document.createElement('div');h.className='v36120-swim';h.innerHTML=`<div class="v36120-head"><strong>Swim distance entry</strong><small>Personal pool helper</small></div><div class="v36120-seg"><label><input type="radio" name="v36120mode" value="lengths" ${p.entryMode!=='distance'?'checked':''}><span>Laps / lengths</span></label><label><input type="radio" name="v36120mode" value="distance" ${p.entryMode==='distance'?'checked':''}><span>Distance</span></label></div><div class="v36120-lengths"><label>Pool<select class="v36120-preset"><option value="home21">Home — 21 yd</option><option value="yd25">25 yd pool</option><option value="m25">25 m pool</option><option value="m50">50 m pool</option><option value="custom">Custom</option></select></label><label>Lengths<input class="v36120-count" type="number" min="0" step="1" inputmode="numeric" placeholder="e.g. 41"></label><div class="v36120-custom" hidden><label>Pool length<input class="v36120-custom-length" type="number" min="0" step="0.1" value="21"></label><label>Unit<select class="v36120-custom-unit"><option value="yd">yd</option><option value="m">m</option><option value="ft">ft</option></select></label></div><small class="v36120-preview">One length = one one-way traversal. Home preset uses 21 yd.</small></div>`;h.querySelector('.v36120-preset').value=p.preset||'home21';(card.querySelector('.log-grid')||card).insertAdjacentElement('afterend',h);h.addEventListener('input',()=>updateSwim(card,h));h.addEventListener('change',()=>updateSwim(card,h));updateSwim(card,h)}
function tissue(state){const s=state.adaptiveModelSnapshot||{},t=s.tissueStress||{},a=Object.entries(t.channels||{}).sort((x,y)=>n(y[1])-n(x[1]))[0];if(!a||n(a[1])<.9)return null;const names={achillesCalf:'lower-leg / Achilles-calf',kneeQuad:'knee / quad',hamstringSpeed:'hamstring / speed',adductorGroin:'adductor / groin',impact:'impact'},ready=!n(s.preparedness)||n(s.preparedness)>=.75;return {headline:ready?`Systemically ready • Recent ${names[a[0]]||a[0]} load elevated`:`Recent ${names[a[0]]||a[0]} mechanical load elevated`,detail:'Mechanical/tissue load is shown separately from systemic fatigue. It is a training-load guard, not an injury prediction.'}}
function status(){let b=document.querySelector('#v36120-status');if(!b){const anchor=document.querySelector('#v36101PerformancePanel')||document.querySelector('.panel');if(!anchor)return;b=document.createElement('div');b.id='v36120-status';b.className='v36120-status';anchor.insertAdjacentElement('afterend',b)}const s=state(),a=recoveryAuthority(s),t=tissue(s);b.innerHTML=`<div><small>Personal calibration</small><strong>${t?.headline||(a.validated?'Personal recovery model validated':'Recovery model still learning')}</strong><p>${t?.detail||''} ${a.note}</p></div><em>${a.validated?'Validated':'Informational'}</em>`}
function weightUI(){const g=weightGate(state());let b=document.querySelector('#v36120-weight');if(!b){const h=[...document.querySelectorAll('h1,h2,h3,h4,strong,.panel-title,.section-title')].find(x=>/body\s*weight|weight tracking/i.test(x.textContent||''));const panel=h?.closest('.panel,section,details,div');if(!panel)return;b=document.createElement('div');b.id='v36120-weight';b.className='v36120-weight';panel.appendChild(b)}b.innerHTML=`<strong>${g.label}</strong><span>${g.ready?`${g.entries} measurements across ${g.spanDays} days.`:`${g.entries}/7 measurements • ${g.spanDays}/14 days. Rate-of-change remains informational.`}</span>`}
function css(){if(document.querySelector('#v36120-css'))return;const s=document.createElement('style');s.id='v36120-css';s.textContent=`.v36120-swim,.v36120-status,.v36120-weight{margin:10px 0;padding:12px;border:1px solid color-mix(in srgb,currentColor 18%,transparent);border-radius:14px;background:color-mix(in srgb,currentColor 4%,transparent)}.v36120-head,.v36120-status{display:flex;justify-content:space-between;gap:12px}.v36120-head small,.v36120-status small,.v36120-status p,.v36120-weight span,.v36120-preview{opacity:.72}.v36120-status strong{display:block}.v36120-status p{margin:4px 0 0;font-size:.86rem}.v36120-status em{font-size:.75rem;font-style:normal;font-weight:700}.v36120-seg{display:flex;gap:8px;margin:10px 0}.v36120-seg label{flex:1}.v36120-seg input{position:absolute;opacity:0}.v36120-seg span{display:block;text-align:center;padding:8px;border:1px solid color-mix(in srgb,currentColor 22%,transparent);border-radius:10px}.v36120-seg input:checked+span{font-weight:700;border-color:currentColor}.v36120-lengths,.v36120-custom{display:grid;grid-template-columns:1fr 1fr;gap:9px}.v36120-lengths>label,.v36120-custom label{display:grid;gap:5px;font-size:.82rem}.v36120-custom,.v36120-preview{grid-column:1/-1}.v36120-lengths[hidden],.v36120-custom[hidden]{display:none!important}.v36120-weight{display:flex;gap:7px;align-items:baseline;flex-wrap:wrap}@media(max-width:560px){.v36120-lengths,.v36120-custom{grid-template-columns:1fr}.v36120-custom,.v36120-preview{grid-column:1}.v36120-status{flex-direction:column}}`;document.head.appendChild(s)}
let busy=false;function refresh(){if(busy)return;busy=true;setTimeout(()=>{busy=false;try{state()}catch{}css();document.querySelectorAll('.log-exercise').forEach(addSwim);status();weightUI()},60)}new MutationObserver(refresh).observe(document.documentElement,{childList:true,subtree:true});
window.HybridPersonalization=Object.freeze({version:VER,resolveDuration:duration,effortCalibration:e=>calibration(e,state()),bodyweightTrendGate:()=>weightGate(state()),recoveryAuthority:()=>recoveryAuthority(state()),swimDistanceFromLengths:swimDistance,getPreferences:prefs,setPreferences:setPrefs,refresh});
refresh();console.info('[Hybrid v36.120] personalization layer active');
})();
